[package]
name = "mdbook-icons"
version = "0.2.3"
edition = "2024"
description = "An mdBook preprocessor that replaces Iconify shortcodes with inline SVG."
license = "MIT"
repository = "https://github.com/ld3z/mdbook-icons"
readme = "README.md"
keywords = ["mdbook", "iconify", "icons"]
categories = ["command-line-utilities", "rendering"]
build = "build.rs"
exclude = ["book/**", "target/**"]

[dependencies]
anyhow = "1"
clap = { version = "4.6.0", features = ["derive"] }
flate2 = "1"
mdbook = "0.4"
once_cell = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
anyhow = "1"
flate2 = "1"
serde = { version = "1", features = ["derive"] }
ureq = { version = "2", features = ["json"] }
tar = "0.4"
