[book]
title = "mdbook-icons"
authors = ["ld3zian"]
language = "en"

[preprocessor.icons]
command = "mdbook-icons"
[preprocessor.icons.aliases]
star = ":twemoji-glowing-star:"
done = ":twemoji-check-mark-button:"
not-done = ":twemoji-hourglass-not-done:"
github = ":mdi-github:"
docker = ":skill-icons-docker:"
rust = ":mdi-language-rust:"

[output.html]
admonitions = true
mathjax-support = false
git-repository-url = "https://github.com/ld3z/mdbook-icons"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/ld3z/mdbook-icons/edit/main/{path}"
no-section-label = true